[package]
name = "utils-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
