[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
anyhow.workspace = true
reqwest = { version = "0.12.9", features = ["blocking"] }
utils-derive = { path = "../utils-derive" }
scraper = "0.21.0"
